Repository Team-AOA/air-mind, pull requests merged in 2022-10, with the labels that each got.

#4 Feat mind map card component
  components/MindMapCard/Modal.jsx
  components/MindMapCard/index.jsx
  components/NodeDetail/index.jsx
  next.config.js
  package.json
  pages/404.jsx
  pages/_app.jsx
  pages/index.jsx
  pages/mind-map/index.jsx
Labels: enhancement

#12 Feature/node canvas 컴포넌트 작성
  .gitignore
  components/Error/404.jsx
  components/Error/500.jsx
  components/Mindmap/index.jsx
  components/Node/index.jsx
  components/NodeCanvas/index.jsx
  components/NodeChildren/index.jsx
  components/NodeHoverOption/index.jsx
  components/NodeWithLine/index.jsx
  components/Nodes/index.jsx
  constants/nodeSize.js
  package-lock.json
  package.json
  pages/_app.jsx
  pages/api/hello.jsx
  pages/error/index.jsx
  store/states.js
  utils/api/mindMapRequests.js
  utils/api/nodeRequests.js
  utils/d3/makeNodeComponentList.jsx
  utils/d3/setMovePosition.js
  utils/d3/zoomPanning.js
  utils/makeNewMindMap.js
Labels: enhancement

#14 Feature/node detail menu
  components/Mindmap/index.jsx
  components/Node/index.jsx
  components/NodeCanvas/index.jsx
  components/NodeComment/index.jsx
  components/NodeDetail/index.jsx
  components/NodeHoverOption/index.jsx
  components/shared/FlexCenterContainer.jsx
  public/images/fast-forward.png
  public/images/noun-drag-and-drop-4076502.png
  public/images/noun-search-5247523.png
  store/states.js
  utils/preventBodyScrolling.js
Labels: enhancement

#16 Feature/create new node
  components/Node/index.jsx
  components/NodeHoverOption/index.jsx
  package-lock.json
  package.json
  service/nodeRequests.js
  utils/d3/calculateNewNodePosition.js
  utils/d3/setMovePosition.js
Labels: enhancement

#17 Feat mindmap 진입 기능 작성
  components/Mindmap/index.jsx
  pages/mind-map/[mindMapId].jsx
  pages/mind-map/index.jsx
  service/mindMapRequests.js
  store/states.js
Labels: enhancement

#18 Feature/login login 구현
  .gitignore
  components/Header/index.jsx
  components/Login/index.jsx
  components/Navbar/index.jsx
  components/shared/Button.jsx
  config/firebase.js
  network/http.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.jsx
  public/images/btn_google_signin_light_pressed_web@2x.png
  service/auth.js
  service/nodeRequests.js
  styles/globals.css
Labels: enhancement, good first issue

#19 Feature/data connect home page
  components/Header/index.jsx
  components/Home/index.jsx
  components/MindMapCard/index.jsx
  components/MindMapInfo/index.jsx
  components/Mindmap/index.jsx
  components/MyWorks/index.jsx
  components/Navbar/index.jsx
  constants/constants.js
  package-lock.json
  pages/mind-map/[mindMapId].jsx
  pages/my-works/index.jsx
  service/mindMapRequests.js
  store/states.js
Labels: enhancement

#20 Feature/save logic
  components/Header/index.jsx
  components/Home/index.jsx
  components/Login/index.jsx
  components/MindMapCard/index.jsx
  components/Mindmap/index.jsx
  components/MyWorks/index.jsx
  components/Navbar/index.jsx
  components/Node/index.jsx
  components/NodeDetail/index.jsx
  components/NodeHoverOption/index.jsx
  components/NodeWithLine/index.jsx
  network/http.js
  package.json
  service/mindMapRequests.js
  store/states.js
  utils/d3/makeNodeComponentList.jsx
  utils/d3/setMovePosition.js
  utils/debounce.js
  utils/pageLoader.js
Labels: enhancement

#22 Feature/node fold delete search
  components/Node/index.jsx
  components/NodeFoldOption/index.jsx
  components/NodeHoverOption/index.jsx
  package.json
  service/nodeRequests.js
  utils/countChildren.js
  utils/d3/calculateNewNodePosition.js
  utils/d3/makeNodeComponentList.jsx
  utils/deleteNodeHelper.js
Labels: enhancement

#23 Feature/drag and drop 이미지 드롭 버그 수정
  components/Header/index.jsx
  components/MindMapInfo/index.jsx
  components/Mindmap/index.jsx
  components/Node/index.jsx
  components/NodeDetail/index.jsx
  components/NodeImageDropZone/index.jsx
  components/shared/ProfileIcon.jsx
  public/images/recycle-bin.png
  store/states.js
Labels: fix

#25 Feature/drag and drop
  components/Header/index.jsx
  components/MindMapInfo/index.jsx
  components/Mindmap/index.jsx
  components/Node/index.jsx
  components/NodeDetail/index.jsx
  components/NodeImageDropZone/index.jsx
  components/shared/ProfileIcon.jsx
  public/images/recycle-bin.png
  store/states.js
Labels: invalid

#27 Fix mindmap 제목, access 수정, 삭제 기능 작성
  components/MindMapInfo/index.jsx
  components/NodeHoverOption/index.jsx
  package-lock.json
Labels: enhancement

#28 Feat node size 변경 기능 작성
  components/NodeHoverOption/index.jsx
Labels: enhancement

#30 Feature/node fetching
  components/Node/index.jsx
  components/NodeFetchButton/index.jsx
  components/NodeFoldOption/index.jsx
  utils/countChildren.js
  utils/d3/makeNodeComponentList.jsx
Labels: enhancement

#33 Feat public 문서의 권한 지정
  components/MindMapInfo/index.jsx
  components/Navbar/index.jsx
  components/Node/index.jsx
  components/NodeDetail/index.jsx
  components/NodeFoldOption/index.jsx
  components/NodeHoverOption/index.jsx
Labels: enhancement

#37 Feature/socket user icon
  components/MindMapCard/index.jsx
  components/Mindmap/index.jsx
  components/Node/index.jsx
  components/NodeCanvas/index.jsx
  components/NodeCoworkers/index.jsx
  components/NodeDetail/index.jsx
  components/NodeFetchButton/index.jsx
  components/NodeFoldOption/index.jsx
  components/NodeHoverOption/index.jsx
  components/NodeWithLine/index.jsx
  network/http.js
  package-lock.json
  store/states.js
  utils/d3/makeNodeComponentList.jsx
  utils/decideSocketUserNode.js
  utils/makeAncestors.js
  utils/socket/receiveSocket.js
Labels: enhancement

#38 Fix socket 이슈 등 수정
  components/Header/index.jsx
  components/MindMapCard/index.jsx
  components/MindMapInfo/index.jsx
  components/Mindmap/index.jsx
  components/Navbar/index.jsx
  components/Node/index.jsx
  components/NodeFoldOption/index.jsx
  constants/constants.js
  next.config.js
  package-lock.json
  service/auth.js
  store/states.js
  utils/deleteNodeHelper.js
  utils/socket/receiveSocket.js
Labels: fix

#40 Fix folding 옵션 오류 수정
  components/MindMapInfo/index.jsx
  components/Mindmap/index.jsx
  components/NodeFoldOption/index.jsx
  utils/socket/receiveSocket.js
Labels: fix

#42 Fix/minor bug report
  components/MindMapCard/index.jsx
  components/Mindmap/index.jsx
  components/NodeCanvas/index.jsx
  components/NodeComment/index.jsx
  components/NodeDetail/index.jsx
  components/NodeHoverOption/index.jsx
  components/NodeImageDropZone/index.jsx
  network/http.js
  next.config.js
  utils/socket/receiveSocket.js
Labels: fix

#44 Fix 유저 아이콘 관련 수정
  components/Node/index.jsx
  components/NodeCanvas/index.jsx
  components/NodeCoworkers/index.jsx
  components/NodeDetail/index.jsx
  components/NodeHoverOption/index.jsx
  utils/socket/receiveSocket.js
Labels: fix

#47 Feat search 기능 추가
  components/mindmap/index.jsx
  components/node/index.jsx
  components/nodehoveroption/index.jsx
  store/states.js
  utils/makesearched.js
Labels: enhancement

#48 Fix search 관련 수정
  components/node/index.jsx
Labels: fix
